### ISSUE TITLE
Boze client crashing when opening menu

### ISSUE THREAD

**Issue by Joao0464** [PlutoSolutions/Boze#62]
---- Minecraft Crash Report ----
// Why is it breaking :(

Time: 2023-01-31 20:57:04
Description: Rendering screen

java.lang.RuntimeException: GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT
	at Not Enough Crashes deobfuscated stack trace.(1.16.5+build.10)
	at net.minecraft.client.gl.Framebuffer.checkFramebufferStatus(Framebuffer:167)
	at dev.boze.client.iH.initFbo(Unknown Source)
	at net.minecraft.client.gl.Framebuffer.resizeInternal(Framebuffer:69)
	at net.minecraft.client.gl.Framebuffer.resize(Framebuffer:58)
	at net.minecraft.class_6367.<init>(class_6367.java:9)
	at dev.boze.client.iG.<init>(Unknown Source)
	at dev.boze.client.iH.<init>(Unknown Source)
	at dev.boze.client.iF.render(Unknown Source)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:881)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1177)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:768)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.client.MinecraftClient.modify$bho000$atTheEndOfFirstCatchBeforePrintingCrashReport(MinecraftClient:8011)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:790)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.client.MinecraftClient.modify$bho000$atTheEndOfFirstCatchBeforePrintingCrashReport(MinecraftClient:8011)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:790)
	at net.minecraft.client.main.Main.method_44604(Main:244)
	at net.minecraft.client.main.Main.main(Main:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_276.method_1239(class_276.java:167)
	at dev.boze.client.iH.method_1231(Unknown Source)
	at net.minecraft.class_276.method_22596(class_276.java:69)
	at net.minecraft.class_276.method_1234(class_276.java:58)
	at net.minecraft.class_6367.<init>(class_6367.java:9)
	at dev.boze.client.iG.<init>(Unknown Source)
	at dev.boze.client.iH.<init>(Unknown Source)
	at dev.boze.client.iF.method_25394(Unknown Source)

-- Screen render details --
Details:
	Screen name: dev.boze.client.iF
	Mouse location: Scaled: (213, 120). Absolute: (427.000000, 240.000000)
	Screen size: Scaled: (427, 240). Absolute: (854, 480). Scale factor of 2.000000
Stacktrace:
	at net.minecraft.class_757.method_3192(class_757.java:881)
	at net.minecraft.class_310.method_1523(class_310.java:1177)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.class_310.modify$bho000$atTheEndOfFirstCatchBeforePrintingCrashReport(class_310.java:8011)
	at net.minecraft.class_310.method_1514(class_310.java:790)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.class_310.modify$bho000$atTheEndOfFirstCatchBeforePrintingCrashReport(class_310.java:8011)
	at net.minecraft.class_310.method_1514(class_310.java:790)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 9 total; [class_746['darlingAlchemy'/54306, l='ClientLevel', x=1000.45, y=149.00, z=1007.13], class_745['CIT-6002c6a772a8'/54308, l='ClientLevel', x=1002.97, y=149.50, z=1008.96], class_745['CIT-0a01300e2a90'/54318, l='ClientLevel', x=1002.27, y=141.00, z=1019.51], class_745['CIT-ab4c8ee6b710'/54328, l='ClientLevel', x=991.99, y=149.50, z=1012.95], class_745['CIT-7ed09f77d81a'/54313, l='ClientLevel', x=1001.95, y=141.00, z=1019.42], class_745['CIT-73f635ef3a29'/54323, l='ClientLevel', x=991.07, y=149.50, z=1017.06], class_745['CIT-a0f159e6407b'/54338, l='ClientLevel', x=1007.48, y=149.00, z=1030.47], class_745['CIT-10cb979a9c85'/54343, l='ClientLevel', x=1009.48, y=149.00, z=1028.47], class_745['CIT-6b7e58da32fb'/54333, l='ClientLevel', x=1005.44, y=149.00, z=1031.45]]
	Chunk stats: 256, 45
	Level dimension: minecraft:the_end
	Level spawn location: World: (-1000,100,-1000), Section: (at 8,4,8 in -63,6,-63; chunk contains blocks -1008,0,-1008 to -993,255,-993), Region: (-2,-2; contains chunks -64,-64 to -33,-33, blocks -1024,0,-1024 to -513,255,-513)
	Level time: 122651830 game time, 122651830 day time
	Server brand: Purpur (Velocity)
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:453)
	at net.minecraft.class_310.method_1587(class_310.java:2341)
	at net.minecraft.class_310.method_1514(class_310.java:787)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.class_310.modify$bho000$atTheEndOfFirstCatchBeforePrintingCrashReport(class_310.java:8011)
	at net.minecraft.class_310.method_1514(class_310.java:790)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.class_310.modify$bho000$atTheEndOfFirstCatchBeforePrintingCrashReport(class_310.java:8011)
	at net.minecraft.class_310.method_1514(class_310.java:790)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 7 (x86) version 6.1
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK Client VM (mixed mode, emulated-client), Microsoft
	Memory: 167043144 bytes (159 MiB) / 570425344 bytes (544 MiB) up to 838860800 bytes (800 MiB)
	CPUs: 2
	Processor Vendor: GenuineIntel
	Processor Name: Pentium(R) Dual-Core  CPU      E5400  @ 2.70GHz
	Identifier: x86 Family 6 Model 23 Stepping 10
	Microarchitecture: Penryn (Client) / Penryn (Server)
	Frequency (GHz): 2.69
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 2
	Graphics card #0 name: Intel(R) G33/G31 Express Chipset Family
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 256.00
	Graphics card #0 deviceId: 0x29c2
	Graphics card #0 versionInfo: DriverVersion=8.15.10.1930
	Virtual memory max (MB): 2038.30
	Virtual memory used (MB): 1655.88
	Swap memory total (MB): 1024.00
	Swap memory used (MB): 551.29
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx800M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	Fabric Mods: 
		baritone: Baritone 1.19.2-SNAPSHOT
		boze: Boze 1.0.1
		dynamicfps: Dynamic FPS 2.2.0
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		enhancedblockentities: Enhanced Block Entities 0.7.2+1.19.2
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.2
			spruceui: SpruceUI 4.0.0+1.19
		fabric-api: Fabric API 0.73.0+1.19.2
			fabric-api-base: Fabric API Base 0.4.14+6e0787e690
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.13+93d8cb8290
			fabric-biome-api-v1: Fabric Biome API (v1) 9.1.0+82db024a90
			fabric-block-api-v1: Fabric Block API (v1) 1.0.2+e415d50e90
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.23+c6af733c90
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.4+b35fea8390
			fabric-command-api-v1: Fabric Command API (v1) 1.2.15+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.2.0+413cbbc790
			fabric-commands-v0: Fabric Commands (v0) 0.2.32+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.40+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.0+7c6cd14d90
			fabric-convention-tags-v1: Fabric Convention Tags 1.2.1+27265b3490
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.8+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.3.6+413cbbc790
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.34+0d0f210290
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.3+9244241690
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.33+562bff6e90
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.34+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.24+b6b6abb490
			fabric-item-api-v1: Fabric Item API (v1) 1.6.4+693ffc0590
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.37+9244241690
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.25+5c4fce2890
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.23+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.3+1b46dc7890
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.11+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.14+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.6+93d8cb8290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.22+33fbc73890
			fabric-models-v0: Fabric Models (v0) 0.3.20+c6af733c90
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.10+10eb22f490
			fabric-networking-v0: Fabric Networking (v0) 0.3.27+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.2.0+d8ef690890
			fabric-particles-v1: Fabric Particles (v1) 1.0.13+4d0d570390
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.0+413cbbc790
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.31+9244241690
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.2.0+2e5408b590
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.7.0+2e5408b590
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.23+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.18+6e0787e690
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.10+4d0d570390
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.26+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 1.12.0+d8ef690890
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.1.2+aae9039d90
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.8.3+251d254a90
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.31+4d0d570390
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.6+1cc24b1b90
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.2+c4f28df590
			fabric-textures-v0: Fabric Textures (v0) 1.0.23+aeb40ebe90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.5+413cbbc790
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.3+08b73de490
		fabricloader: Fabric Loader 0.14.13
		ferritecore: FerriteCore 5.0.3
		java: OpenJDK Client VM 17
		lazydfu: LazyDFU 0.1.3
		lithium: Lithium 0.10.4
		minecraft: Minecraft 1.19.2
		notenoughcrashes: Not Enough Crashes 4.2.1+1.19.2
		phosphor: Phosphor 0.8.1
		reeses-sodium-options: Reese's Sodium Options 1.4.9+mc1.19.2-build.67
		sodium: Sodium 0.4.4+build.18
			org_joml_joml: joml 1.10.4
		sodium-extra: Sodium Extra 0.4.16+mc1.19.2-build.90
			caffeineconfig: CaffeineConfig 1.0.0+1.17
	Launched Version: fabric-loader-0.14.13-1.19.2
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: llvmpipe (LLVM 8.0, 128 bits) GL version 3.3 (Core Profile) Mesa 20.1.8, VMware, Inc.
	Window size: 854x480
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: id=1, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_OPERATION in glTexImage2DMultisample(samples=4)' x 1
id=1, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_FRAMEBUFFER_OPERATION in glClear(incomplete framebuffer)' x 1
id=1, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_ENUM in glPolygonMode(face)' x 2
id=1, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_OPERATION in glTexImage2DMultisample(samples=4)' x 1
id=1, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_FRAMEBUFFER_OPERATION in glClear(incomplete framebuffer)' x 1
id=1, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_ENUM in glPolygonMode(face)' x 2
id=1, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_OPERATION in glTexImage2DMultisample(samples=4)' x 1
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: Fabric Mods
	Current Language: Português (Brasil)
	CPU: 2x Pentium(R) Dual-Core CPU E5400 @ 2.70GHz
	Client Crashes Since Restart: 3
	Integrated Server Crashes Since Restart: 0
	Suspected Mods: Minecraft (minecraft), Fabric Loader (fabricloader), Boze (boze), Not Enough Crashes (notenoughcrashes)

**Comment by mr-nv** [comment]
Backend API: llvmpipe (LLVM 8.0, 128 bits) GL version 3.3 (Core Profile) Mesa 20.1.8, VMware, Inc.

try removing all mods except boze baritone sodium and fabric api, or if that wont work then maybe your vm's gpu drivers are old
